import {Metadata} from "next";
import { Inter, Manrope, Roboto} from "next/font/google";
import "./globals.css";


const inter = Roboto({
    subsets: ["latin"],
    style: "normal",
    weight: "400"
});

export const metadata: Metadata = {
    title: "Sales Management",
    description: "Generated by Benjamin"
}

export default function RootLayout ({
    children,
}: Readonly<{children: React.ReactNode;}>) {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    )
}